version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "coolify.buildpack=true"
      - "coolify.buildpack.builder=heroku/buildpacks:20" 