[phases.setup]
nixPkgs = ['nodejs', 'nginx']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'nginx -g "daemon off;"'

[nginx]
root = '/app/build'
locations = { "/scan/" = "try_files $uri $uri/ /scan/index.html;" }
port = "80"

[env]
PORT = "80"
NODE_ENV = "production"
HOST = "0.0.0.0" 